Internet Banking/Internet Banking/Controllers/UserPageController.cs
using System;
using System.Web.Mvc;
using System.Web.Security;
using InternetBankingDal;
using InternetBankingDal.Providers.Implements;
using Internet_Banking.Models;
using Internet_Banking.Services.Implements;
using Internet_Banking.Services.Interfaces;

namespace Internet_Banking.Controllers
{
    [Authorize]
    public class UserPageController : Controller
    {
        private readonly GenericDataRepository<AdditionalUserData> _repositoryUser = new GenericDataRepository<AdditionalUserData>();

        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            FormsAuthentication.SignOut();
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        //
        // POST: /UserPage/Login

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid && Membership.ValidateUser(model.UserName, model.Password))
            {
                var userData = _repositoryUser.GetSingle(x => x.UserId == (Guid)Membership.GetUser(model.UserName).ProviderUserKey);
                if (userData != null && userData.IsTemporary)
                    return View("CreatePassword", new CreatePasswordModel() { UserName = model.UserName });
                FormsAuthentication.SetAuthCookie(model.UserName, false);
                return RedirectToLocal(returnUrl);
            }
            var membershipUser = Membership.GetUser();
            if (membershipUser != null && membershipUser.IsLockedOut)
                ModelState.AddModelError("", "Пользователь заблокирован.");
            else
            // If we got this far, something failed, redisplay form
                ModelState.AddModelError("", "Введен неверный логин или пароль. Для восстановления необходимо обратиться в отделение МБанка (при себе иметь паспорт).");
            return View(model);
        }

        //
        // POST: /UserPage/LogOff

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        //
        // GET: /UserPage/Register

        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        //
        // POST: /UserPage/Register

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                // Attempt to register the user
                try
                {
                    Membership.CreateUser(model.UserName, model.Password);
                    FormsAuthentication.SetAuthCookie(model.UserName, false);
                   // WebSecurity.Login(model.UserName, model.Password);
                    return RedirectToAction("Index", "Home");
                }
                catch (MembershipCreateUserException e)
                {
                    ModelState.AddModelError("", ErrorCodeToString(e.StatusCode));
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /UserPage/Manage

        public ActionResult Manage(ManageMessageId? message)
        {
            ViewBag.StatusMessage =
                message == ManageMessageId.ChangePasswordSuccess ? "Ваш пароль был изменен."
                : message == ManageMessageId.SetPasswordSuccess ? "Your password has been set."
                : message == ManageMessageId.RemoveLoginSuccess ? "The external login was removed."
                : "";
            ViewBag.ReturnUrl = Url.Action("Manage");
            return View();
        }

        //
        // POST: /UserPage/Manage

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Manage(LocalPasswordModel model)
        {
            ViewBag.ReturnUrl = Url.Action("Manage");
            if (ModelState.IsValid)
            {
                // ChangePassword will throw an exception rather than return false in certain failure scenarios.
                bool changePasswordSucceeded;
                try
                {
                    changePasswordSucceeded = Membership.Provider.ChangePassword(User.Identity.Name, model.OldPassword,
                        model.NewPassword);
                }
                catch (Exception)
                {
                    changePasswordSucceeded = false;
                }

                if (changePasswordSucceeded)
                {
                    return RedirectToAction("Manage", new {Message = ManageMessageId.ChangePasswordSuccess});
                }
                ModelState.AddModelError("", "Пароли введены некорректно.");
            }
            
            // If we got this far, something failed, redisplay form
            return View(model);
        }
        //
        // GET: /UserPage/CreatePassword
        public ActionResult CreatePassword(ManageMessageId? message, string userName)
        {
            ViewBag.UserName = userName;
            ViewBag.StatusMessage =
                message == ManageMessageId.ChangePasswordSuccess ? "Ваш пароль был изменен."
                : message == ManageMessageId.SetPasswordSuccess ? "Ваш пароль успешно установлен."
                : message == ManageMessageId.RemoveLoginSuccess ? "The external login was removed."
                : "";
            ViewBag.ReturnUrl = Url.Action("Manage");
            return View();
        }

        //
        // POST: /UserPage/CreatePassword

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult CreatePassword(CreatePasswordModel model)
        {
            if (ModelState.IsValid)
            {
                var user = Membership.GetUser(model.UserName);
                // ChangePassword will throw an exception rather than return false in certain failure scenarios.
                bool setPasswordSuccess;
                try
                {
// ReSharper disable once PossibleNullReferenceException
                    setPasswordSuccess = user.ChangePassword(user.ResetPassword(), model.NewPassword);
                    //Membership.Provider.ChangePassword(User.Identity.Name, oldPassword, model.NewPassword);
                }
                catch (Exception)
                {
                    setPasswordSuccess = false;
                }

                if (setPasswordSuccess)
                {
                    FormsAuthentication.SetAuthCookie(model.UserName, false);

                    var userData =
                        _repositoryUser.GetSingle(
                            x => user.ProviderUserKey != null && x.UserId == (Guid) user.ProviderUserKey);
                    userData.IsTemporary = false;
                    _repositoryUser.Update(userData);
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", "Пароли введены некорректно.");
            }
             //If we got this far, something failed, redisplay form
            return View(model);
        }

        #region Helpers
        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        public enum ManageMessageId
        {
            ChangePasswordSuccess,
            SetPasswordSuccess,
            RemoveLoginSuccess,
        }
        private static string ErrorCodeToString(MembershipCreateStatus createStatus)
        {
            // See http://go.microsoft.com/fwlink/?LinkID=177550 for
            // a full list of status codes.
            switch (createStatus)
            {
                case MembershipCreateStatus.DuplicateUserName:
                    return "User name already exists. Please enter a different user name.";

                case MembershipCreateStatus.DuplicateEmail:
                    return "A user name for that e-mail address already exists. Please enter a different e-mail address.";

                case MembershipCreateStatus.InvalidPassword:
                    return "The password provided is invalid. Please enter a valid password value.";

                case MembershipCreateStatus.InvalidEmail:
                    return "The e-mail address provided is invalid. Please check the value and try again.";

                case MembershipCreateStatus.InvalidAnswer:
                    return "The password retrieval answer provided is invalid. Please check the value and try again.";

                case MembershipCreateStatus.InvalidQuestion:
                    return "The password retrieval question provided is invalid. Please check the value and try again.";

                case MembershipCreateStatus.InvalidUserName:
                    return "The user name provided is invalid. Please check the value and try again.";

                case MembershipCreateStatus.ProviderError:
                    return "The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator.";

                case MembershipCreateStatus.UserRejected:
                    return "The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator.";

                default:
                    return "An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator.";
            }
        }
        #endregion
    }
}

Internet Banking/Internet Banking/Views/UserPage/CreatePassword.cshtml
@model Internet_Banking.Models.CreatePasswordModel

@{
    ViewBag.Title = "CreatePassword";
}

<h2>Вы воспользовались временным паролем. Создайте новый пароль.</h2>

@using (Html.BeginForm("CreatePassword", "UserPage", new{ userName = Model.UserName}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>CreatePasswordModel</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.NewPassword)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NewPassword)
            @Html.ValidationMessageFor(model => model.NewPassword)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ConfirmPassword)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ConfirmPassword)
            @Html.ValidationMessageFor(model => model.ConfirmPassword)
        </div>

        <p>
            <input type="submit" value="Изменить пароль" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("К начальной странице.", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Internet Banking/Internet Banking/Views/UserPage/Login.cshtml
@model Internet_Banking.Models.LoginModel
@{
    ViewBag.Title = "Вход в систему";
}

<hgroup class="title textcentred">
    <h1>@ViewBag.Title</h1>
</hgroup>
<hr/>

<p class="text-center pagination-left">
    <strong>Уважаемые клиенты!</strong><br/><br/>
    Мы настоятельно рекомендуем вам ознакомиться с правилами по работе с интернет-банком «Мбанк». 
    Если у вас есть подозрения, что вас пытаются обмануть, сообщите об этом в телефонный центр 
    нашего банка по номеру, указанному на обратной стороне вашей карты.<br/>
</p>

<section class="loginForm centred form-horizontal bordered">
<p><br/></p>
@using (Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

            <div class="control-group">
                <label class="control-label">
                    @Html.LabelFor(m => m.UserName)
                </label>
                <div class="controls unstyled">
                    @Html.TextBoxFor(m => m.UserName)
                    @Html.ValidationMessageFor(m => m.UserName)
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">
                    @Html.LabelFor(m => m.Password)
                </label>
                <div class="controls unstyled">
                    @Html.PasswordFor(m => m.Password)
                    @Html.ValidationMessageFor(m => m.Password)
                </div>
                
            </div>
    
    <div class="control-group">
        <div class="controls">
            <input type="submit" class="btn-success text-center" value="Войти">
        </div>
    </div>
}
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Internet Banking/Internet Banking/Views/UserPage/Manage.cshtml
@model Internet_Banking.Models.LocalPasswordModel
@{
    ViewBag.Title = "Управление профилем";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>

<p class="message-success">@ViewBag.StatusMessage</p>

<p>Вы вошли как <strong>@User.Identity.Name</strong>.</p>

@Html.Partial("_ChangePasswordPartial")

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Internet Banking/Internet Banking/Views/UserPage/Register.cshtml
@model Internet_Banking.Models.RegisterModel
@{
    ViewBag.Title = "Регистрация";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>Создайте новый аккаунт.</h2>
</hgroup>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <fieldset>
        <legend>Registration Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.UserName)
                @Html.TextBoxFor(m => m.UserName)
            </li>
            <li>
                @Html.LabelFor(m => m.Password)
                @Html.PasswordFor(m => m.Password)
            </li>
            <li>
                @Html.LabelFor(m => m.ConfirmPassword)
                @Html.PasswordFor(m => m.ConfirmPassword)
            </li>
        </ol>
        <input type="submit" value="Register" />
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Internet Banking/Internet Banking/Views/UserPage/_ChangePasswordPartial.cshtml
@model Internet_Banking.Models.LocalPasswordModel

<h3>Смена пароля</h3>

@using (Html.BeginForm("Manage", "UserPage")) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <fieldset>
        <legend>Change Password Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.OldPassword)
                @Html.PasswordFor(m => m.OldPassword)
            </li>
            <li>
                @Html.LabelFor(m => m.NewPassword)
                @Html.PasswordFor(m => m.NewPassword)
            </li>
            <li>
                @Html.LabelFor(m => m.ConfirmPassword)
                @Html.PasswordFor(m => m.ConfirmPassword)
            </li>
        </ol>
        <input type="submit" value="Изменить пароль" />
    </fieldset>
}